name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  GO_VERSION: 1.20

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:

      # step 1: Set up go
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
      
      # step 2: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # step 3: Install dependencies
      - name: Install Go dependencies
        run: go get
      
      # step 4: Run test
      - name: go test
        run: go test

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [test]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

    

