
name: "CI - ${{ github.event.head_commit.message }}"
on:
  push:
    branches:
      - "*"
env:
  GO_VERSION: 1.20
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:

      # step 1: set up go
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
      
      # step 2: checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # step 3: install dependencies
      - name: Install Go dependencies
        run: go get
      
      # step 4: run test
      - name: go test
        run: go test
    

